name: my_analysis_options
description: The analysis options for my projects.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter_lints: ^2.0.1

dev_dependencies:
  test: ^1.16.0
